### ISSUE TITLE
jQuery errors using WP 3.5beta1 and buddyPress 1.7

### ISSUE THREAD

**Issue by anointed** [boonebgorges/bp-groupblog#17]
using groupblog with WP 3.5beta1 and buddypress 1.7 leads to the following error showing up.

themes/p2-buddypress/groupblog/_inc/custom.js line 162
Error: TypeError: $ is undefined
[Break On This Error] 	
....style.height=h+"px";e.valLength=vlen;e.boxWidth=ewidth}return true};this.each(f...

**Comment by boonebgorges** [comment]
Looks like this was fixed via #20. Thanks!
