### ISSUE TITLE
users should log out of the main community

### ISSUE THREAD

**Issue by gautamshelley** [boonebgorges/bp-groupblog#42]
I've installed boss theme integrated it with buddypress groupblog. Now the thing comes up that whenever a user is logged in and is reading one of the blogs , let us suppose he's reading www.emptysheets.com/lifequotes (viz. a groupblog) : after reading this blog if he logs out, he's redirected to www.emptysheets.com/lifequotes/wp-admin rather than going to www.emptysheets.com/wp-admin . how can i change this ?

**Comment by boonebgorges** [comment]
Hi @gautamshelley - Thanks for the ticket!

How is the user logging out? That is, exactly what button/link is he pressing? Is it something in the toolbar? The code that generates each logout link is, generally speaking, responsible for telling WP how it'd like to be redirected after the logout occurs. I'm not sure this is something that bp-groupblog should be responsible for (it depends on the specifics of the logout link you're thinking of) but I can probably point you in the right direction to modify the behavior on your own installation.

**Comment by gautamshelley** [comment]
Well the problem's solved now anyways :-)
