### ISSUE TITLE
Warning on php line 18

### ISSUE THREAD

**Issue by CannabisProphet** [boonebgorges/bp-groupblog#43]
This appears in the group..
Warning: include(): Filename cannot be empty in /home/forcannabis/public_html/wp-content/plugins/bp-groupblog/groupblog/inc/activity.php on line 18

Warning: include(): Failed opening '' for inclusion (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/forcannabis/public_html/wp-content/plugins/bp-groupblog/groupblog/inc/activity.php on line 18
![screenshot-forcannabis us 2016-12-11 09-53-32](https://cloud.githubusercontent.com/assets/12688464/21081245/e6cfe7b4-bf87-11e6-8dd1-9bdca4ae1ec6.png)

**Comment by boonebgorges** [comment]
Thanks for the report. It looks like this might indicate that 
bp-groupblog is not fully compatible with themes that use BP's theme 
compatibilty layer.

Can you share more details about what theme you're using?
